name: "Test Suite"

# Controls when the workflow will run
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run in parallel
jobs:
  # Job to run tests
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run tests
        run: cargo test --all-features

  # Job to check formatting
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchain with rustfmt
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Check formatting
        uses: actions-rust-lang/rustfmt@v1

  # Job to lint the code with clippy
  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchain with clippy
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Lint with clippy
        # Treat all warnings as errors
        run: cargo clippy -- -D warnings